# Generated by Django 5.1.4 on 2024-12-19 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='specialty',
            field=models.TextField(blank=True),
        ),
    ]
